eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:9001/eureka
    instance:
        instance-id: easygo-ad-service-9004
        ip-address: 127.0.0.1
        prefer-ip-address: true
mybatis:
    mapper-locations: classpath:mappers/*.xml
server:
    port: 9004
spring:
    application:
        name: easygo-ad-service
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        druid:
            initial-size: 1
            max-active: 20
            min-idle: 1
            stat-view-servlet:
                allow: true
            test-on-borrow: true
        password: root
        url: jdbc:mysql://127.0.0.1:3306/springcloud02?useUnicode=true&characterEncoding=utf-8
        username: root
